26 contact us page with bootstraps
elishevarom/employee-accounts pull request #34
Opened 2024-06-25 00:07 UTC by ChanaMar2

Added a contact page and configured with bootstraps

2024-06-25 00:25 UTC, Egrosberg approved these changes

2024-06-25 03:00 UTC, etamiller requested changes
Mrs. Rom said:
The node_modules should be being ignored and they're not so something must have gone wrong with the .gitignore file or the node_modules got placed in the wrong folder
... they have to be deleted from the branch before continuing

2024-06-26 02:25 UTC, etamiller approved these changes

2024-06-26 18:11 UTC, SerachS approved these changes
it says there are conflicts with the main which i guess you'll fix before you merge

2024-06-27 14:10 UTC, merged