delete page design updated#1
elishevarom/employee-accounts pull request #58
Opened 2024-07-11 01:42 UTC by etamiller

2024-07-11 21:56 UTC, Egrosberg approved these changes
Very nice! I like that it gives a warning before deleting.

2024-07-12 00:53 UTC, elishevarom requested changes
Seems like most of the css can be accomplished with bootstrap's built in classes. Ask chatgpt. Just paste your css file in and ask how you would use react bootstrap for this css file

2024-07-14 15:31 UTC, ChanaMar2 approved these changes

2024-07-21 13:12 UTC, elishevarom approved these changes

2024-08-01 15:34 UTC, SerachS approved these changes

2024-08-09 16:00 UTC, closed without merging